name: Run Checks
on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Enable Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: clang-format
          cache: yes

      - name: Use Homebrew clang-format
        run: |
          brew link --overwrite --force clang-format >/dev/null
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          clang-format --version

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check Code formatting
        run: bun run format:check

      - name: Run tests
        run: bun run test:coverage
