# Checks if the PR title follows semantic commit message conventions
name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  lint-pr-title:
    uses: OneSignal/sdk-actions/.github/workflows/lint-pr-title.yml@main
    secrets: inherit
